apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stock-anomaly-detection
  name: finnhub-news-producer
  labels:
    app: finnhub-news-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finnhub-news-producer
  template:
    metadata:
      labels:
        app: finnhub-news-producer
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z openhouse-kafka 9092; do
                echo "waiting for kafka..."; sleep 3
              done
              echo "kafka is ready"
      containers:
        - name: finnhub-news-producer
          image: hungvt0110/finnhub-news-producer:v0.1
          imagePullPolicy: Always
          env:
            - name: FINNHUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: finnhub-trades-producer-secrets
                  key: FINNHUB_API_KEY
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "openhouse-kafka:9092"
            - name: KAFKA_TOPIC
              value: "raw.stock.news"
            - name: POLL_INTERVAL_SEC
              value: "300"
            - name: LOOKBACK_DAYS
              value: "2"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
