apiVersion: v1
kind: Secret
metadata:
  namespace: stock-anomaly-detection
  name: finnhub-trades-producer-secrets
type: Opaque
stringData:
  FINNHUB_API_KEY: "d7l3j9pr01qm7o0acfs0d7l3j9pr01qm7o0acfsg"
